### ISSUE TITLE
我执行命令报错了

### ISSUE THREAD

**Issue by nanjizhilian** [codeliuyang/django_mysql_comment#2]
我的verbose_name="部门"
是这样的，但是还是报错
尝试verbose_name='部门'
也是报错

    model_comment_sql += original_ddl + " COMMENT '" + str(verbose_name) + "'"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by codeliuyang** [comment]
确实是写到model里面去了吗？Django版本什么的是？

**Comment by nanjizhilian** [comment]
确实写进去了，django版本3.2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月31日(周二) 中午1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [codeliuyang/django_databse_column_comment] 我执行命令报错了 (Issue #2)




 
确实是写到model里面去了吗？Django版本什么的是？

**Comment by codeliuyang** [comment]
我测试了一下3.2版本，倒是可以的...

**Comment by Zhaoyuhang97** [comment]
相同的问题~
![image](https://user-images.githubusercontent.com/49008009/228751614-62af4bb2-6d79-4e70-8821-445ff736325c.png)

**Comment by codeliuyang** [comment]
可以看一下data_asset的Model代码吗，以及你的数据库驱动是

**Comment by Zhaoyuhang97** [comment]
我的字段类型为onetoone，将此处verbose_name删除掉恢复正常，所以我觉得以下源码 此处需要增加判断吧？？？
![image](https://user-images.githubusercontent.com/49008009/228754531-f48cb5b9-08e6-4a15-b842-2183a98dc1fa.png)

**Comment by Zhaoyuhang97** [comment]
使用verbose_name作为comments，个人觉得help_text更像是备注而verbose_name像是一个别名，后续可以将这两个字段都加入到comments的备选中，help_text优先

**Comment by codeliuyang** [comment]
okay，好建议

**Comment by codeliuyang** [comment]
已增加help_text，如果同时存在还是verbose_name优先
